-
  name: Copy a python file, edit and execute
  hosts: target1
  user: root

  tasks:
    - name: Copy a local python file to the target
      copy: 
        src: hello.py
        dest: /home/osboxes/Documents
    
    - name: Putting a new line in a file
      lineinfile:
        dest: /home/osboxes/Documents/hello.py
        line: "print('putting a line in the end of the file')"

    - name: Exec the py file
      command: python /home/osboxes/Documents/hello.py

